name: Github Actions
run-name: |
  Running CI for remark-automatic-glossary-markup
on:
  push:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
