name: Github Actions
run-name: Running CI for remark-automatic-glossary-markup
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: npm install
      - run: npm run lint
      - run: npm run test
